repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: pretty-format-json
    -   id: mixed-line-ending
  